//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CenterReservation.DL.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACPatient
    {
        public ACPatient()
        {
            this.TRANVisits = new HashSet<TRANVisit>();
        }
    
        public int PatientID { get; set; }
        public string PatientName { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> Age { get; set; }
    
        public virtual ICollection<TRANVisit> TRANVisits { get; set; }
    }
}
