//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CenterReservation.DL.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BDPhysician
    {
        public BDPhysician()
        {
            this.BDPhysicianSalaries = new HashSet<BDPhysicianSalary>();
            this.TRANVisits = new HashSet<TRANVisit>();
        }
    
        public int PhysicianID { get; set; }
        public string PhysicianName { get; set; }
    
        public virtual ICollection<BDPhysicianSalary> BDPhysicianSalaries { get; set; }
        public virtual ICollection<TRANVisit> TRANVisits { get; set; }
    }
}
