//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CenterReservation.DL.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BDVisitPrice
    {
        public int VisitPriceID { get; set; }
        public int VisitTypeID { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public decimal VisitPrice { get; set; }
    
        public virtual BDVisitType BDVisitType { get; set; }
    }
}
