//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CenterReservation.DL.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BDVisitType
    {
        public BDVisitType()
        {
            this.BDVisitPrices = new HashSet<BDVisitPrice>();
            this.TRANVisits = new HashSet<TRANVisit>();
        }
    
        public int VisitTypeID { get; set; }
        public string VisitTypeName { get; set; }
    
        public virtual ICollection<BDVisitPrice> BDVisitPrices { get; set; }
        public virtual ICollection<TRANVisit> TRANVisits { get; set; }
    }
}
