//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CenterReservation.DL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BDPhysicianSalary
    {
        public int PhysicianPriceID { get; set; }
        public int PhysicianID { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public decimal PhysicianSalary { get; set; }
    
        public virtual BDPhysician BDPhysician { get; set; }
    }
}
